name: Fullstack CI/CD with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_BACKEND: ghcr.io/${{ github.repository }}-backend
      IMAGE_FRONTEND: ghcr.io/${{ github.repository }}-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend Docker image
        run: docker build -t $IMAGE_BACKEND:latest ./backend

      - name: Push backend Docker image
        run: docker push $IMAGE_BACKEND:latest

      - name: Build frontend Docker image
        run: docker build -t $IMAGE_FRONTEND:latest ./frontend

      - name: Push frontend Docker image
        run: docker push $IMAGE_FRONTEND:latest
